<!DOCTYPE html>
<?php
   session_start();
   if(!isset($_SESSION['user_name']))
   {
       header("location:login.php");
       $user_id=$_SESSION['user_id'];
   }
   $charity_id=$_POST['charity_id'];
   $rs=$_POST['rs'];
   
   ?>  
<html lang="en">
   <head>
      <title>PAYMENT</title>
   </head>
   <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container">
    <div class="row">
        <div class="well col-xs-10 col-sm-10 col-md-6 col-xs-offset-1 col-sm-offset-1 col-md-offset-3">
            <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <address>
                        <strong>WeCharity</strong>
                       
                    </address>
                </div>
                <?php
                        include'connect.php';
                        $sql=$link->rawQuery("select * from charity INNER JOIN user ON user.user_id=charity.charity_id
                        INNER JOIN charity_donation ON charity_donation.charity_id=charity.charity_id");
                        if($link->count>0)
                        {
                            foreach($sql as $data)
                            {
                                $charity_name=$data['charity_name'];
                                $user_name=$data['user_name'];
                            }
                        }
                    ?>
                <div class="col-xs-6 col-sm-6 col-md-6 text-right">
                    <p>
                </div>
                        <em>NAME OF DONOR : <?=$data['user_name'];?></em>
                    </p>
                   
            </div>
            <?php
                $apikey = "rzp_test_tB0N3KreyNLVpg";
                $rs=$_POST['rs'];
            ?>
            <div class="row">
                <div class="text-center">
                    <h1>Receipt</h1>
                </div>
                </span>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Charity</th>
                            <th class="text-center">Total</th>
                        </tr>
                    </thead>
                   
                    <tbody>
                        <tr>
                            <td class="col-md-12"><em><?=$charity_name;?></em></h4></td>
                            <td class="col-md-1 text-center"> <?=$rs;?></td>
                        </tr>
                        <tr>
                            <td class="text-right"><h4><strong>Total: </strong></h4></td>
                            <td class="text-center text-danger"><h4><strong><?=$rs;?></strong></h4></td>
                        </tr>
                    </tbody>
                </table>
             
<form action="pay_php.php" method="POST">
<input type="hidden" name="charity_id" value="<?=$charity_id?>">
<input type="hidden" name="rs" value="<?=$rs?>">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?=$apikey;?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?=$rs*100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?='OID'.rand(10,100).'END';?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="WeCharity"
    data-description="Charity"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name=""
    data-prefill.email=""
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>
            </div>
        </div>
    </div>
</html>