<?php
    $apikey = "rzp_test_tB0N3KreyNLVpg";
    $rs=$_POST['rs'];
?>
<form action="pay_php.php" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?=$apikey;?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?=$rs*100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?='OID'.rand(10,100).'END';?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="WeCharity"
    data-description="Charity"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name=""
    data-prefill.email=""
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>